{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "owncloud-dashboard.serviceAccountName" . }}
  labels:
{{ include "owncloud-dashboard.labels" . | nindent 4 }}
{{- end -}}
